# Generated by Django 4.0.4 on 2022-05-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_imagegallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_ru',
            new_name='title',
        ),
    ]
