# Generated by Django 4.0.4 on 2022-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image_miniature',
            field=models.ImageField(blank=True, upload_to='product_photo/', verbose_name='Главное изображение миниатюра'),
        ),
    ]
