# Generated by Django 4.0.4 on 2022-05-26 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('main_image', models.ImageField(blank=True, upload_to='product_photo/', verbose_name='Главное изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('serial_number', models.CharField(max_length=150, verbose_name='Серийный номер')),
                ('location', models.CharField(choices=[('warehouse', 'Склад'), ('office_gorgasali', 'Офис Горкасали 9'), ('house', 'Дом'), ('office_gorizont', 'Офис Горизонт')], default='office_gorgasali', max_length=200, verbose_name='Локация')),
                ('place_of_application', models.CharField(choices=[('kitchen', 'Кухня'), ('Toilet', 'Туалет'), ('bar', 'Бар'), ('lower_hall', 'Нижний зал'), ('upper_hall', 'Верхний зал'), ('smart_office', 'Смарт офис'), ('reception', 'Ресепшн')], default='reception', max_length=200, verbose_name='Место применения')),
                ('equipment', models.TextField(blank=True, verbose_name='Комплектация')),
                ('warranty', models.DateTimeField(blank=True, verbose_name='Дата, с которой исчисляется гарантийный срок')),
                ('additional_information', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('status', models.CharField(choices=[('serviceable', 'Исправен'), ('requires_repair', 'Требует ремонта'), ('write-downs', 'Списание'), ('missing', 'Пропажа'), ('Requires an extension', 'Требует дополнение'), ('on_the_hands', 'На руках')], default='serviceable', max_length=200, verbose_name='Статус')),
                ('main_image_miniature', models.ImageField(blank=True, upload_to='product_photo/', verbose_name='Главное изображение миниатюра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category', verbose_name='Категория')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Материальная ценность',
                'verbose_name_plural': 'Материальные ценности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('additional_picture', models.ImageField(blank=True, upload_to='product_photo/', verbose_name='Дополнительное изображение')),
                ('additional_picture_miniature', models.ImageField(upload_to='product_photo/', verbose_name='Дополнительное изображение миниатюра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Материальная ценность')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
                'ordering': ['-created_at'],
            },
        ),
    ]
