# Generated by Django 4.0.4 on 2022-05-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_title_ru_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image_miniature',
        ),
    ]
