# Generated by Django 4.0.4 on 2022-05-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_main_image_miniature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='Серийный номер'),
        ),
    ]
