# Generated by Django 4.0.4 on 2022-05-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.DateField(blank=True, null=True, verbose_name='Дата, с которой исчисляется гарантийный срок'),
        ),
    ]
