# Generated by Django 3.2.4 on 2022-05-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_main_image_miniature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Гарантийный срок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('warehouse', 'Склад'), ('office_gorgasali', 'Офис на ул. Горгасали 9'), ('house', 'Дом'), ('office_gorizont', 'Офис Горизонт')], default='office_gorgasali', max_length=200, verbose_name='Локация'),
        ),
    ]
